name: Platform IO

on:
  push:
    branches: []
  pull_request:
    branches: []
  schedule:
    - cron: "0 1 * * 6" # Every Saturday at 1AM

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: "pio:${{ matrix.target }}:${{ matrix.platform }}"
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        platform: [
          "stable"
        ]
        target:
          [
            "BRINEOMATIC_REV_B",
            "BRINEOMATIC_REV_C",
            "FROTHFET_REV_E",
            "SENDIT_REV_C"
          ]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*' # Use '20' or 'lts/*' for the latest stable version
          #cache: 'npm'       # Automatically caches your node_modules based on package-lock.json

      - name: Install dependencies
        run: npm install

      - name: Cache PlatformIO
        uses: actions/cache@v4
        with:
          key: ${{ matrix.target }}-pio-${{ hashFiles('platformio.ini') }}
          restore-keys: |
            ${{ matrix.target }}-pio-
          path: |
            ~/.cache/pip
            ~/.platformio
            .pio/libdeps

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install Platform IO
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio

      - name: Install Library
        run: pio pkg install -e ${{ matrix.target }}

      - run: PIO_PLATFORM="https://github.com/pioarduino/platform-espressif32/releases/download/${{ matrix.platform }}/platform-espressif32.zip" pio run -e ${{ matrix.target }}
